name: clash_royale_assistant
description: Stats Royale Assistant helps you enjoy Clash Royale more by providing the most accurate statistics possible.
homepage: https://app.sadra.at/clash-royale-assistant
repository: https://github.com/xsadra/clash-royale-assistant.git
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  equatable: ^2.0.2
  data_connection_checker: ^0.3.4
  dartz: ^0.9.2
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  flutter_bloc: ^7.0.1
  get_it: ^7.1.3
  sailor: ^0.7.1
  flutter_staggered_animations: ^1.0.0
  convex_bottom_bar: ^3.0.0
  charts_flutter: ^0.10.0
  auto_route: ^0.6.9
  timeago: ^3.1.0
  url_launcher:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  auto_route_generator:  ^0.6.10
  analyzer: 1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ui/
    - assets/images/chests/
    - assets/images/arena/
    - assets/images/cards/
    - assets/images/cards-gold/
    - assets/images/clan-badges/
    - assets/images/crown/